type = "service_account"
project_id = "tcr-app-3ca2e"
storageBucket = "tcr-app-3ca2e.firebasestorage.app"
private_key_id = "4db3f222df9242f3deb7a4a4809f71bf0c498570"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCzIgew9B1/lFSx
TTuUmQH5ukw7P97c9A/jMrFy/Xh+hub17vImRMAuWD7UuWyMOdlIrG4JFmvpr7FT
GFTUXYOObIvE+3T20eOWH4nXaByJnl/uZOQTmwLP5Aa6GgzF426SqGSlQXOu2E6x
of68mzCebusaRSCipD9tINzrwHvGNs7qa7qbCiA7iZGoi48yvWW7h8wB/ID9J8Ty
p2tvfdJvJNjhPyFDynEzuSOhdsIHVPLBJn9kmH4oKO4uMd/R7iw/PUfO0v/VRDA4
WNNa4jZRtFyba3P/08taaaWyKxxS1GnV4nNbHxcc+26LUskkzRe4luKJeuf8AGFA
U04w6hXfAgMBAAECggEAF7xuoHf4YKta/ZNqTapopJqW91LjSQvd/xD8imwjx0BA
4l2jIIcDoCB5Ut6vD3Wq4QJYIkQiUHjDWmti8jDh+cFQU+2t9fah3YaYUT6uaV3f
AEvGHQLxQHLKoWZKQv577Fr72xntJkHrS4ZXps45hwTTikuWo3Z4IRG1tFdxDzaC
zqtIMofdjdT9/7oN02iyCqjbMdcpOnpu+Kt6PnrgImgGDCu55kUmAN0LaxSUdOeP
OmKKAn+mXAoVpxaQG3sYmNx/P6K0JLPCI9JnstJRC0wIHFBaU5oxwotvg/04SaDk
8lArgOZHl9xPvNL4FxlTjHMWqxHccFmIwTW2qxVagQKBgQDyFhR/xLgBgVp5+IoR
to4e+7lNlBFLt2HqaRvzrZOj0saD2wz/TnIfhKXy/cOtPWKBcIiuut/s1FLJ2F9a
hn/lVev/uWFUISKZCKakNNkUopOIlFdZcAIznzVZtxpt8gPnGDaqzNH0tLpqQRLc
hgfbKYMz557nXx/7Yx/ibBH1bwKBgQC9bbDDVTLeh6PWGpol8mHSB4iDicvAXhLt
5vtJPXW4TR937BVq5AoDcedQ8f9FF2sv0CbS/aEx0rQDhPuyogGN5jgpa9IEKN95
Av0xtOSUuXkqkbyH34QUlavOD63bkyFxyLjvyoE9WO1su18HFz2rtAaAWENQJGyR
4m81gM4OkQKBgAh8H6HOykg7OWmW/XfbdyW82uTOMMD/n23w2yryRX9zbsPGVLFK
FZPnOU3H+SjEQwSYZiIBqMGLO4+ZhtYMasUl+syOucuSEb1dYUHWHFmtzQ/3awxW
ca1PgjYvxbxexCZAYgIghadXAkWhHEEgbXwP+2pBTv97BQrxkXeFJCf/AoGBALUB
fpl37O7Ej6JDsy41aJGID0MZxa8gdVgMketPJhCg6UPvPBvyoTrfeVhYlULQ+OQs
Mx0DrCbunoKKbPQpZ/DOnrW9yGWfJML+PzBjGNSgUg6CSbNPumbtCckSJGAfPCL8
2PKQ/2O+eMigVlJxO8W5dUjojhGjbHcN9pQaa0txAoGBAMGXbW3U9DyJ8y6fzYfk
viaVU9ymzVDATtbIb16y7ILsiljBxZxGxX1e208jEovpk3PqsTXrTA/4MT2k8Ly9
AwthyvU4ATEdoJ1zfkZ+cjUIWAPJGpfyCO2FfJFCUGb02TlRhwBRUcCOLGtmY3zp
yexiAgE3fTJcBL1mxcObExed
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@tcr-app-3ca2e.iam.gserviceaccount.com"
client_id = "105816414200662802122"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40tcr-app-3ca2e.iam.gserviceaccount.com"